### ISSUE TITLE
Question : this does only work for microsoft images?

### ISSUE THREAD

**Issue by StefH** [Kymeric/DockerProxy#2]
When running a dotnet Linux based container **microsoft/dotnet:2.0-runtime-deps**, the line 

`20:23:36.738 [] [Information] Proxying - localhost:9090 -> 172.17.82.143:80`

never appears.

Probably because of last comment here : https://github.com/docker/for-win/issues/204 ?

**Update**
Note that this is tested on Windows 10 host.

**Comment by StefH** [comment]
For Linux you don't need this tool ? Correct ? Because I think the vpnkit.exe or docker itself handles all fine.

**Comment by jbankes** [comment]
Hey @StefH, 

I'm not a DockerProxy guy but I've been looking at this topic myself. [This comment](https://github.com/docker/for-win/issues/204#issuecomment-258638899) on a different project explains a bit. With that said, you are correct and don't need this tool on Linux hosts.

**Comment by StefH** [comment]
@jbankes Indeed, I did some more testing and you don't need this tool for Linux. I think that maybe the `vpnkit.exe` takes care of that?

But the reason why I did not work on Windows was that I made a programming error in my application.
