### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by 1oglop1** [Kymeric/DockerProxy#5]
Hello, 

I'm experimenting with small python app in windowscore container, app is running on `localhost:8888` in container.
And I want to expose it at `9999` on `HOST` according to all articles `docker run -p` does not work on widows.

And your program seems to be the only thing which let's to access it from `docker HOST` at `localhost:9999`

Do you maybe have step by step guide? because what ever I did
I could not get `Proxying ...` sentence in console

Do you mind pointing me to guide how to build the project?
executing `build.ps1` does not work out of the box.

**Comment by 1oglop1** [comment]
This was the problem `var nat = Container.NetworkSettings.Networks["nat"];` please update Readme that it reads only default `nat` netowrk

**Comment by jonstelly** [comment]
[Readme updated to call-out 'nat' networking](https://github.com/Kymeric/DockerProxy/commit/0c46d64eac95d8062a8cf8f631740502882b570b), thanks for filing the issue.

**Comment by 1oglop1** [comment]
Thanks for the Readme update.

Do you mind pointing me how to build it from source?
I found the fork should handle various networks.
