### ISSUE TITLE
SQL Server container not visible on localhost:1433

### ISSUE THREAD

**Issue by pbar1** [Kymeric/DockerProxy#7]
I'm running SQL Server 2016 in a Docker Windows container - I can connect just fine to the SQL server instance in SSMS using the container IP. 

I've tried the latest release of DockerProxy as well as building from source, but I can't seem to connect to the SQL server instance from either SSMS or sqlcmd on `localhost` or `127.0.0.1`. DockerProxy seems to indicate that it is working:

`15:51:11.162 [] [Information] Proxying - localhost:1433 -> 172.24.220.242:1433`

Any ideas?

**Comment by StefH** [comment]
Do you run DockerProxy as administrator.
